### ISSUE TITLE
SparkFun RedBoard Artemis Nano python serial output not working on Linux

### ISSUE THREAD

**Issue by jomoengineer** [PacktPublishing/TinyML-Cookbook_2E#2]
I've been going through the projects in the book, and in Chapter 2 where it has running the serial to Google Driver example, I am not able to get this to work with the SparkFun RedBoard Artemis Nano. It works with a Arduino 33 BLE nano, but not the SparkFun board.

I tried to build and load the following driver for Linux but it still does not work:
https://www.wch-ic.com/downloads/CH341SER_ZIP.html

I had to edit the brltty rules and comment out the id for 7523 to get the driver to load:

> sudo view /usr/lib/udev/rules.d/85-brltty.rules

```
# Device: 1A86:7523
# Baum [NLS eReader Zoomax (20 cells)]
#ENV{PRODUCT}=="1a86/7523/*", ENV{BRLTTY_BRAILLE_DRIVER}="bm", GOTO="brltty_usb_run"

```

The driver comes up as ttyUSB0 but this still does not produce any serial output on Linux. It works in the Arduino IDE on Windows, but not with pyserial on Ubuntu 22.04. 

Same issue with a Raspberry Pi running Bullseye. 

Any suggestions?

**Comment by jomoengineer** [comment]
Okay, I did find that the driver from WCH did work
[https://www.wch-ic.com/downloads/CH341SER_ZIP.html](https://www.wch-ic.com/downloads/CH341SER_ZIP.html)

I had an issue in my script for the baudrate which was not an issue with the 33 BLE Nano but caused an error with the Artemis Nano. 
It's working now.

**Comment by gmiodice** [comment]
Hi @jomoengineer I am glad to know you managed to solve the issue. Do not hesitate to open a new one if you need any help.
